---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install open jdk 
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
  - name: start service
    service:
     name: "{{myjavapackonubuntu}}"
     state: started
     



  
