---
- hosts: 172.31.81.192
  become: yes
  tasks:
  - include_tasks: includetaskEg.yml

  - name: i want to copy file from ansible master to ansible node
    copy:
      src: mymasterstaticfile
      dest: /home/ubuntu/mystaticfile

  - name: i want to install web server 
    apt:
      name: apache2
      state: present

  - name: copy dunamic file from node to master nodes
    template: 
       src: dynamicfile.j2
       dest: /var/www/html/index.html