---
- hosts: 172.31.81.192
  become: yes
  tasks:
  - name: show o/p of first task on console
    apt:
      name: apache2
      state: present

  - name: install git 
    apt:
      name: git
      state: present

  - name: install tree
    apt:
      name: tree 
      state: present